import tkinter as tk
from tkinter import messagebox
import joblib
import numpy as np
import requests
import pandas as pd
from urllib.parse import quote

from rdkit import Chem
from rdkit.Chem import AllChem

# File paths
MODEL_FILE = r"E:\subjects\DDI project\model\ddi_smiles_model.pkl"
ORIGINAL_CSV_FILE = r"E:\subjects\DDI project\dataset\db_drug_interactions.csv"

# Load model
model = joblib.load(MODEL_FILE)

# Load original dataset directly
original_df = pd.read_csv(ORIGINAL_CSV_FILE)
original_df.columns = ['drug1', 'drug2', 'interaction_description']
original_df = original_df.dropna().drop_duplicates()

def get_smiles_from_pubchem(drug_name):
    encoded_name = quote(str(drug_name).strip())
    url = f"https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/{encoded_name}/property/ConnectivitySMILES/JSON"

    try:
        response = requests.get(url, timeout=15)
        if response.status_code == 200:
            data = response.json()
            props = data.get("PropertyTable", {}).get("Properties", [])
            if props and "ConnectivitySMILES" in props[0]:
                return props[0]["ConnectivitySMILES"]
    except Exception:
        return None

    return None

def smiles_to_fingerprint(smiles, radius=2, n_bits=2048):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    fp = AllChem.GetMorganFingerprintAsBitVect(mol, radius, nBits=n_bits)
    arr = np.array(fp)
    return arr

def predict_interaction():
    drug1 = drug1_var.get().strip()
    drug2 = drug2_var.get().strip()

    if not drug1 or not drug2:
        messagebox.showwarning("Warning", "Please enter both drug names.")
        return

    if drug1.lower() == drug2.lower():
        messagebox.showwarning("Warning", "Please enter two different drugs.")
        return

    result_text.config(state="normal")
    desc_text.config(state="normal")
    result_text.delete("1.0", tk.END)
    desc_text.delete("1.0", tk.END)

    # First: search exact pair in original CSV dataset
    result = original_df[
        ((original_df['drug1'].str.lower() == drug1.lower()) & (original_df['drug2'].str.lower() == drug2.lower())) |
        ((original_df['drug1'].str.lower() == drug2.lower()) & (original_df['drug2'].str.lower() == drug1.lower()))
    ]

    if not result.empty:
        result_text.insert(
            tk.END,
            "Known interaction found in the original dataset.\n"
            "Prediction source: recorded dataset entry."
        )
        result_text.config(fg="#155724")

        for _, row in result.iterrows():
            desc_text.insert(tk.END, row['interaction_description'] + "\n")

        result_text.config(state="disabled")
        desc_text.config(state="disabled")
        return

    # If not found in original dataset, use PubChem + model
    result_text.insert(tk.END, "Fetching SMILES from PubChem...\n")
    root.update()

    smiles1 = get_smiles_from_pubchem(drug1)
    smiles2 = get_smiles_from_pubchem(drug2)

    if smiles1 is None:
        messagebox.showerror("Error", f"Could not retrieve SMILES for '{drug1}' from PubChem.")
        result_text.config(state="disabled")
        desc_text.config(state="disabled")
        return

    if smiles2 is None:
        messagebox.showerror("Error", f"Could not retrieve SMILES for '{drug2}' from PubChem.")
        result_text.config(state="disabled")
        desc_text.config(state="disabled")
        return

    fp1 = smiles_to_fingerprint(smiles1)
    fp2 = smiles_to_fingerprint(smiles2)

    if fp1 is None or fp2 is None:
        messagebox.showerror("Error", "Failed to convert SMILES to molecular fingerprints.")
        result_text.config(state="disabled")
        desc_text.config(state="disabled")
        return

    combined_fp = np.concatenate([fp1, fp2]).reshape(1, -1)

    prediction = model.predict(combined_fp)[0]
    probability = model.predict_proba(combined_fp)[0]
    score = max(probability) * 100

    result_text.delete("1.0", tk.END)

    if prediction == 1:
        result_text.insert(
            tk.END,
            f"Potential interaction detected.\n"
            f"Prediction score: {score:.2f}%\n"
            f"Prediction source: SMILES-based machine learning model."
        )
        result_text.config(fg="#155724")

        desc_text.insert(
            tk.END,
            "No exact interaction record was found in the original dataset.\n"
            "This result was generated by the model using molecular structure features."
        )
    else:
        result_text.insert(
            tk.END,
            f"No interaction predicted.\n"
            f"Prediction score: {score:.2f}%\n"
            f"Prediction source: SMILES-based machine learning model."
        )
        result_text.config(fg="#721c24")

        desc_text.insert(
            tk.END,
            "No exact interaction record was found in the original dataset.\n"
            "This result was generated by the model using molecular structure features."
        )

    result_text.config(state="disabled")
    desc_text.config(state="disabled")

def clear_fields():
    drug1_var.set("")
    drug2_var.set("")

    result_text.config(state="normal")
    desc_text.config(state="normal")
    result_text.delete("1.0", tk.END)
    desc_text.delete("1.0", tk.END)
    result_text.config(state="disabled")
    desc_text.config(state="disabled")

# Main window
root = tk.Tk()
root.title("Drug-Drug Interaction Predictor v2")
root.geometry("860x650")
root.configure(bg="#f8f9fa")

title_label = tk.Label(
    root,
    text="Drug-Drug Interaction Predictor",
    font=("Segoe UI", 24, "bold"),
    bg="#f8f9fa",
    fg="#1f3b73"
)
title_label.pack(pady=20)

warning_frame = tk.Frame(root, bg="#fff3cd", bd=1, relief="solid")
warning_frame.pack(fill="x", padx=30, pady=10)

warning_label = tk.Label(
    warning_frame,
    text=(
        "Professional Use Only\n"
        "This tool is intended for physicians and pharmacists only. "
        "It must not be used by patients for self-medication or treatment decisions."
    ),
    font=("Segoe UI", 11, "bold"),
    bg="#fff3cd",
    fg="#856404",
    wraplength=720,
    justify="center",
    padx=10,
    pady=10
)
warning_label.pack()

form_frame = tk.Frame(root, bg="#f8f9fa")
form_frame.pack(pady=20)

tk.Label(form_frame, text="Drug 1:", font=("Segoe UI", 12, "bold"), bg="#f8f9fa").grid(row=0, column=0, padx=10, pady=12, sticky="w")
drug1_var = tk.StringVar()
drug1_entry = tk.Entry(form_frame, textvariable=drug1_var, font=("Segoe UI", 11), width=40)
drug1_entry.grid(row=0, column=1, padx=10, pady=12)

tk.Label(form_frame, text="Drug 2:", font=("Segoe UI", 12, "bold"), bg="#f8f9fa").grid(row=1, column=0, padx=10, pady=12, sticky="w")
drug2_var = tk.StringVar()
drug2_entry = tk.Entry(form_frame, textvariable=drug2_var, font=("Segoe UI", 11), width=40)
drug2_entry.grid(row=1, column=1, padx=10, pady=12)

button_frame = tk.Frame(root, bg="#f8f9fa")
button_frame.pack(pady=10)

predict_button = tk.Button(
    button_frame,
    text="Predict Interaction",
    font=("Segoe UI", 12, "bold"),
    bg="#007bff",
    fg="white",
    activebackground="#0056b3",
    activeforeground="white",
    padx=18,
    pady=8,
    relief="flat",
    command=predict_interaction
)
predict_button.grid(row=0, column=0, padx=10)

clear_button = tk.Button(
    button_frame,
    text="Clear",
    font=("Segoe UI", 12, "bold"),
    bg="#6c757d",
    fg="white",
    activebackground="#545b62",
    activeforeground="white",
    padx=18,
    pady=8,
    relief="flat",
    command=clear_fields
)
clear_button.grid(row=0, column=1, padx=10)

tk.Label(root, text="Prediction Result", font=("Segoe UI", 12, "bold"), bg="#f8f9fa", fg="#343a40").pack()
result_text = tk.Text(root, height=4, width=82, font=("Segoe UI", 11), bd=1, relief="solid")
result_text.pack(pady=8)
result_text.config(state="disabled")

tk.Label(root, text="Interaction Description", font=("Segoe UI", 12, "bold"), bg="#f8f9fa", fg="#343a40").pack()
desc_text = tk.Text(root, height=10, width=82, font=("Segoe UI", 11), bd=1, relief="solid")
desc_text.pack(pady=8)
desc_text.config(state="disabled")

footer_label = tk.Label(
    root,
    text="Hybrid system: recorded dataset lookup + SMILES-based machine learning prediction.",
    font=("Segoe UI", 10, "italic"),
    bg="#f8f9fa",
    fg="gray"
)
footer_label.pack(pady=10)

root.mainloop()
